title: Beating the urge to cheat
description: Recipes to combat weight loss craving. Delicious recipes and blog
  post about food and recipe books
footer_text: Copyright 2021 Hannah Smith
header_feature_image: ../uploads/max-delsid-ioz4kesuy1e-unsplash.jpg
header_text: Beating the Urge to Cheat
header_text_color: "#121212"
bannerheight: 20vmax
logo: ../uploads/dan-gold-4_jhdo54byg-unsplash.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
